# Generated by Django 4.0.2 on 2022-02-03 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_ticket_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
